// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: types.proto

package types

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Identity struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Identity) Reset()         { *m = Identity{} }
func (m *Identity) String() string { return proto.CompactTextString(m) }
func (*Identity) ProtoMessage()    {}
func (*Identity) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_10d2a9060a8367f5, []int{0}
}
func (m *Identity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identity.Unmarshal(m, b)
}
func (m *Identity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identity.Marshal(b, m, deterministic)
}
func (dst *Identity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identity.Merge(dst, src)
}
func (m *Identity) XXX_Size() int {
	return xxx_messageInfo_Identity.Size(m)
}
func (m *Identity) XXX_DiscardUnknown() {
	xxx_messageInfo_Identity.DiscardUnknown(m)
}

var xxx_messageInfo_Identity proto.InternalMessageInfo

func (m *Identity) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Identity) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Identity) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type CreateChannelTx struct {
	AddressSigned        string   `protobuf:"bytes,1,opt,name=address_signed,json=addressSigned,proto3" json:"address_signed,omitempty"`
	PubKey               string   `protobuf:"bytes,2,opt,name=pub_key,json=pubKey,proto3" json:"pub_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateChannelTx) Reset()         { *m = CreateChannelTx{} }
func (m *CreateChannelTx) String() string { return proto.CompactTextString(m) }
func (*CreateChannelTx) ProtoMessage()    {}
func (*CreateChannelTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_10d2a9060a8367f5, []int{1}
}
func (m *CreateChannelTx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateChannelTx.Unmarshal(m, b)
}
func (m *CreateChannelTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateChannelTx.Marshal(b, m, deterministic)
}
func (dst *CreateChannelTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateChannelTx.Merge(dst, src)
}
func (m *CreateChannelTx) XXX_Size() int {
	return xxx_messageInfo_CreateChannelTx.Size(m)
}
func (m *CreateChannelTx) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateChannelTx.DiscardUnknown(m)
}

var xxx_messageInfo_CreateChannelTx proto.InternalMessageInfo

func (m *CreateChannelTx) GetAddressSigned() string {
	if m != nil {
		return m.AddressSigned
	}
	return ""
}

func (m *CreateChannelTx) GetPubKey() string {
	if m != nil {
		return m.PubKey
	}
	return ""
}

type MapEntry struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MapEntry) Reset()         { *m = MapEntry{} }
func (m *MapEntry) String() string { return proto.CompactTextString(m) }
func (*MapEntry) ProtoMessage()    {}
func (*MapEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_10d2a9060a8367f5, []int{2}
}
func (m *MapEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapEntry.Unmarshal(m, b)
}
func (m *MapEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapEntry.Marshal(b, m, deterministic)
}
func (dst *MapEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapEntry.Merge(dst, src)
}
func (m *MapEntry) XXX_Size() int {
	return xxx_messageInfo_MapEntry.Size(m)
}
func (m *MapEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_MapEntry.DiscardUnknown(m)
}

var xxx_messageInfo_MapEntry proto.InternalMessageInfo

func (m *MapEntry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *MapEntry) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type TokenMeta struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	Decimals             int32    `protobuf:"varint,3,opt,name=Decimals,proto3" json:"Decimals,omitempty"`
	InitialSupply        int64    `protobuf:"varint,4,opt,name=InitialSupply,proto3" json:"InitialSupply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenMeta) Reset()         { *m = TokenMeta{} }
func (m *TokenMeta) String() string { return proto.CompactTextString(m) }
func (*TokenMeta) ProtoMessage()    {}
func (*TokenMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_10d2a9060a8367f5, []int{3}
}
func (m *TokenMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenMeta.Unmarshal(m, b)
}
func (m *TokenMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenMeta.Marshal(b, m, deterministic)
}
func (dst *TokenMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenMeta.Merge(dst, src)
}
func (m *TokenMeta) XXX_Size() int {
	return xxx_messageInfo_TokenMeta.Size(m)
}
func (m *TokenMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenMeta.DiscardUnknown(m)
}

var xxx_messageInfo_TokenMeta proto.InternalMessageInfo

func (m *TokenMeta) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TokenMeta) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *TokenMeta) GetDecimals() int32 {
	if m != nil {
		return m.Decimals
	}
	return 0
}

func (m *TokenMeta) GetInitialSupply() int64 {
	if m != nil {
		return m.InitialSupply
	}
	return 0
}

type NewChannelPostTx struct {
	Version              int32    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Cid                  string   `protobuf:"bytes,3,opt,name=cid,proto3" json:"cid,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewChannelPostTx) Reset()         { *m = NewChannelPostTx{} }
func (m *NewChannelPostTx) String() string { return proto.CompactTextString(m) }
func (*NewChannelPostTx) ProtoMessage()    {}
func (*NewChannelPostTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_10d2a9060a8367f5, []int{4}
}
func (m *NewChannelPostTx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewChannelPostTx.Unmarshal(m, b)
}
func (m *NewChannelPostTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewChannelPostTx.Marshal(b, m, deterministic)
}
func (dst *NewChannelPostTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewChannelPostTx.Merge(dst, src)
}
func (m *NewChannelPostTx) XXX_Size() int {
	return xxx_messageInfo_NewChannelPostTx.Size(m)
}
func (m *NewChannelPostTx) XXX_DiscardUnknown() {
	xxx_messageInfo_NewChannelPostTx.DiscardUnknown(m)
}

var xxx_messageInfo_NewChannelPostTx proto.InternalMessageInfo

func (m *NewChannelPostTx) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *NewChannelPostTx) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *NewChannelPostTx) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *NewChannelPostTx) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type SubscribeIdentittyTx struct {
	Statt                int32    `protobuf:"varint,1,opt,name=statt,proto3" json:"statt,omitempty"`
	ConversationPubKey   []byte   `protobuf:"bytes,2,opt,name=conversation_pub_key,json=conversationPubKey,proto3" json:"conversation_pub_key,omitempty"`
	EncryptedMessage     string   `protobuf:"bytes,3,opt,name=encrypted_message,json=encryptedMessage,proto3" json:"encrypted_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeIdentittyTx) Reset()         { *m = SubscribeIdentittyTx{} }
func (m *SubscribeIdentittyTx) String() string { return proto.CompactTextString(m) }
func (*SubscribeIdentittyTx) ProtoMessage()    {}
func (*SubscribeIdentittyTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_10d2a9060a8367f5, []int{5}
}
func (m *SubscribeIdentittyTx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeIdentittyTx.Unmarshal(m, b)
}
func (m *SubscribeIdentittyTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeIdentittyTx.Marshal(b, m, deterministic)
}
func (dst *SubscribeIdentittyTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeIdentittyTx.Merge(dst, src)
}
func (m *SubscribeIdentittyTx) XXX_Size() int {
	return xxx_messageInfo_SubscribeIdentittyTx.Size(m)
}
func (m *SubscribeIdentittyTx) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeIdentittyTx.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeIdentittyTx proto.InternalMessageInfo

func (m *SubscribeIdentittyTx) GetStatt() int32 {
	if m != nil {
		return m.Statt
	}
	return 0
}

func (m *SubscribeIdentittyTx) GetConversationPubKey() []byte {
	if m != nil {
		return m.ConversationPubKey
	}
	return nil
}

func (m *SubscribeIdentittyTx) GetEncryptedMessage() string {
	if m != nil {
		return m.EncryptedMessage
	}
	return ""
}

type SubscribeChannelTx struct {
	Deposit              int32    `protobuf:"varint,1,opt,name=deposit,proto3" json:"deposit,omitempty"`
	SubscriptionPubKey   []byte   `protobuf:"bytes,2,opt,name=subscription_pub_key,json=subscriptionPubKey,proto3" json:"subscription_pub_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeChannelTx) Reset()         { *m = SubscribeChannelTx{} }
func (m *SubscribeChannelTx) String() string { return proto.CompactTextString(m) }
func (*SubscribeChannelTx) ProtoMessage()    {}
func (*SubscribeChannelTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_10d2a9060a8367f5, []int{6}
}
func (m *SubscribeChannelTx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeChannelTx.Unmarshal(m, b)
}
func (m *SubscribeChannelTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeChannelTx.Marshal(b, m, deterministic)
}
func (dst *SubscribeChannelTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeChannelTx.Merge(dst, src)
}
func (m *SubscribeChannelTx) XXX_Size() int {
	return xxx_messageInfo_SubscribeChannelTx.Size(m)
}
func (m *SubscribeChannelTx) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeChannelTx.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeChannelTx proto.InternalMessageInfo

func (m *SubscribeChannelTx) GetDeposit() int32 {
	if m != nil {
		return m.Deposit
	}
	return 0
}

func (m *SubscribeChannelTx) GetSubscriptionPubKey() []byte {
	if m != nil {
		return m.SubscriptionPubKey
	}
	return nil
}

type Null struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Null) Reset()         { *m = Null{} }
func (m *Null) String() string { return proto.CompactTextString(m) }
func (*Null) ProtoMessage()    {}
func (*Null) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_10d2a9060a8367f5, []int{7}
}
func (m *Null) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Null.Unmarshal(m, b)
}
func (m *Null) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Null.Marshal(b, m, deterministic)
}
func (dst *Null) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Null.Merge(dst, src)
}
func (m *Null) XXX_Size() int {
	return xxx_messageInfo_Null.Size(m)
}
func (m *Null) XXX_DiscardUnknown() {
	xxx_messageInfo_Null.DiscardUnknown(m)
}

var xxx_messageInfo_Null proto.InternalMessageInfo

type WrapStr struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WrapStr) Reset()         { *m = WrapStr{} }
func (m *WrapStr) String() string { return proto.CompactTextString(m) }
func (*WrapStr) ProtoMessage()    {}
func (*WrapStr) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_10d2a9060a8367f5, []int{8}
}
func (m *WrapStr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WrapStr.Unmarshal(m, b)
}
func (m *WrapStr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WrapStr.Marshal(b, m, deterministic)
}
func (dst *WrapStr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WrapStr.Merge(dst, src)
}
func (m *WrapStr) XXX_Size() int {
	return xxx_messageInfo_WrapStr.Size(m)
}
func (m *WrapStr) XXX_DiscardUnknown() {
	xxx_messageInfo_WrapStr.DiscardUnknown(m)
}

var xxx_messageInfo_WrapStr proto.InternalMessageInfo

func (m *WrapStr) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type WrapInt struct {
	Value                int64    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WrapInt) Reset()         { *m = WrapInt{} }
func (m *WrapInt) String() string { return proto.CompactTextString(m) }
func (*WrapInt) ProtoMessage()    {}
func (*WrapInt) Descriptor() ([]byte, []int) {
	return fileDescriptor_types_10d2a9060a8367f5, []int{9}
}
func (m *WrapInt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WrapInt.Unmarshal(m, b)
}
func (m *WrapInt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WrapInt.Marshal(b, m, deterministic)
}
func (dst *WrapInt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WrapInt.Merge(dst, src)
}
func (m *WrapInt) XXX_Size() int {
	return xxx_messageInfo_WrapInt.Size(m)
}
func (m *WrapInt) XXX_DiscardUnknown() {
	xxx_messageInfo_WrapInt.DiscardUnknown(m)
}

var xxx_messageInfo_WrapInt proto.InternalMessageInfo

func (m *WrapInt) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*Identity)(nil), "Identity")
	proto.RegisterType((*CreateChannelTx)(nil), "CreateChannelTx")
	proto.RegisterType((*MapEntry)(nil), "MapEntry")
	proto.RegisterType((*TokenMeta)(nil), "TokenMeta")
	proto.RegisterType((*NewChannelPostTx)(nil), "NewChannelPostTx")
	proto.RegisterType((*SubscribeIdentittyTx)(nil), "SubscribeIdentittyTx")
	proto.RegisterType((*SubscribeChannelTx)(nil), "SubscribeChannelTx")
	proto.RegisterType((*Null)(nil), "Null")
	proto.RegisterType((*WrapStr)(nil), "WrapStr")
	proto.RegisterType((*WrapInt)(nil), "WrapInt")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_types_10d2a9060a8367f5) }

var fileDescriptor_types_10d2a9060a8367f5 = []byte{
	// 450 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0xed, 0x8a, 0xd3, 0x40,
	0x14, 0xa5, 0xf6, 0xfb, 0xba, 0xab, 0x75, 0x28, 0x5a, 0x14, 0x71, 0x09, 0x0a, 0x0b, 0x82, 0x88,
	0x3e, 0xc2, 0xea, 0x8f, 0x22, 0x2d, 0x6b, 0x52, 0xf0, 0x67, 0x9c, 0x24, 0xd7, 0xdd, 0x61, 0x93,
	0x99, 0x61, 0xe6, 0x66, 0xb7, 0xf3, 0x0c, 0xbe, 0xb4, 0xcc, 0x24, 0xd3, 0x76, 0xc1, 0x7f, 0xf7,
	0x9c, 0x73, 0xc9, 0x39, 0x67, 0x2e, 0x81, 0xa7, 0xe4, 0x34, 0xda, 0x4f, 0xda, 0x28, 0x52, 0x49,
	0x01, 0xb3, 0x75, 0x85, 0x92, 0x04, 0x39, 0xf6, 0x16, 0xe0, 0x8f, 0x30, 0x96, 0x72, 0xc9, 0x1b,
	0x5c, 0x0d, 0x2e, 0x06, 0x97, 0xf3, 0x74, 0x1e, 0x98, 0x2d, 0x6f, 0x90, 0xbd, 0x81, 0x79, 0xcd,
	0xa3, 0xfa, 0x24, 0xa8, 0x33, 0x4f, 0x04, 0xf1, 0x35, 0xcc, 0x5a, 0x8b, 0x26, 0x68, 0xc3, 0x4e,
	0x8b, 0x38, 0xf9, 0x09, 0xcf, 0xaf, 0x0c, 0x72, 0xc2, 0xab, 0x5b, 0x2e, 0x25, 0xd6, 0xbb, 0x3d,
	0xfb, 0x00, 0xcf, 0x78, 0x55, 0x19, 0xb4, 0x36, 0xb7, 0xe2, 0x46, 0x62, 0xd5, 0xdb, 0x9d, 0xf7,
	0x6c, 0x16, 0x48, 0xf6, 0x0a, 0xa6, 0xba, 0x2d, 0xf2, 0x3b, 0x74, 0xbd, 0xe1, 0x44, 0xb7, 0xc5,
	0x0f, 0x74, 0xc9, 0x17, 0x98, 0x6d, 0xb8, 0xfe, 0x2e, 0xc9, 0x38, 0xb6, 0x80, 0xa1, 0x5f, 0xe8,
	0x3e, 0xe0, 0x47, 0xb6, 0x84, 0xf1, 0x3d, 0xaf, 0xdb, 0x98, 0xb2, 0x03, 0x89, 0x83, 0xf9, 0x4e,
	0xdd, 0xa1, 0xdc, 0x20, 0x71, 0xc6, 0x60, 0xb4, 0x3d, 0xb6, 0x0c, 0x33, 0x7b, 0x09, 0x93, 0xcc,
	0x35, 0x85, 0xaa, 0xa3, 0x59, 0x87, 0x7c, 0xb7, 0x6f, 0x58, 0x8a, 0x86, 0xd7, 0x36, 0x74, 0x1b,
	0xa7, 0x07, 0xcc, 0xde, 0xc3, 0xf9, 0x5a, 0x0a, 0x12, 0xbc, 0xce, 0x5a, 0xad, 0x6b, 0xb7, 0x1a,
	0x5d, 0x0c, 0x2e, 0x87, 0xe9, 0x63, 0x32, 0xb9, 0x85, 0xc5, 0x16, 0x1f, 0xfa, 0xfa, 0xd7, 0xca,
	0xd2, 0x6e, 0xcf, 0x56, 0x30, 0xbd, 0x47, 0x63, 0x85, 0x92, 0x21, 0xc4, 0x38, 0x8d, 0xd0, 0xc7,
	0x57, 0x0f, 0x12, 0x4d, 0x8c, 0x1f, 0x80, 0xaf, 0x59, 0x8a, 0xaa, 0x7f, 0x5c, 0x3f, 0xfa, 0x0e,
	0x15, 0x27, 0x1e, 0x2c, 0xcf, 0xd2, 0x30, 0x27, 0x7f, 0x07, 0xb0, 0xcc, 0xda, 0xc2, 0x96, 0x46,
	0x14, 0xd8, 0x5f, 0x96, 0xdc, 0x6e, 0xef, 0x3f, 0x6a, 0x89, 0x13, 0xf5, 0x66, 0x1d, 0x60, 0x9f,
	0x61, 0x59, 0x2a, 0xe9, 0x8d, 0x39, 0x09, 0x25, 0xf3, 0xd3, 0xd7, 0x3e, 0x4b, 0xd9, 0xa9, 0x76,
	0x1d, 0x5e, 0x9e, 0x7d, 0x84, 0x17, 0x28, 0x4b, 0xe3, 0x34, 0x61, 0x95, 0x37, 0x68, 0x2d, 0xbf,
	0x89, 0x17, 0x5f, 0x1c, 0x84, 0x4d, 0xc7, 0x27, 0xbf, 0x81, 0x1d, 0xc2, 0x1c, 0x8f, 0xbf, 0x82,
	0x69, 0x85, 0x5a, 0x59, 0x11, 0xc3, 0x44, 0xe8, 0xe3, 0xd8, 0x6e, 0x5f, 0xff, 0x2f, 0xce, 0xa9,
	0xd6, 0xc5, 0x49, 0x26, 0x30, 0xda, 0xb6, 0x75, 0x9d, 0xbc, 0x83, 0xe9, 0x2f, 0xc3, 0x75, 0x46,
	0xe6, 0x78, 0xfd, 0xc1, 0xe9, 0xf5, 0xfb, 0x85, 0xb5, 0xa4, 0xc7, 0x0b, 0xc3, 0x7e, 0xa1, 0x98,
	0x84, 0x1f, 0xe2, 0xeb, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc1, 0x50, 0x1d, 0xf3, 0x1f, 0x03,
	0x00, 0x00,
}
