// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: entities.proto

package entities

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Identity struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Username             string   `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Identity) Reset()         { *m = Identity{} }
func (m *Identity) String() string { return proto.CompactTextString(m) }
func (*Identity) ProtoMessage()    {}
func (*Identity) Descriptor() ([]byte, []int) {
	return fileDescriptor_entities_8415b24e7cc06108, []int{0}
}
func (m *Identity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Identity.Unmarshal(m, b)
}
func (m *Identity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Identity.Marshal(b, m, deterministic)
}
func (dst *Identity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Identity.Merge(dst, src)
}
func (m *Identity) XXX_Size() int {
	return xxx_messageInfo_Identity.Size(m)
}
func (m *Identity) XXX_DiscardUnknown() {
	xxx_messageInfo_Identity.DiscardUnknown(m)
}

var xxx_messageInfo_Identity proto.InternalMessageInfo

func (m *Identity) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Identity) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Identity) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type MapEntry struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MapEntry) Reset()         { *m = MapEntry{} }
func (m *MapEntry) String() string { return proto.CompactTextString(m) }
func (*MapEntry) ProtoMessage()    {}
func (*MapEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_entities_8415b24e7cc06108, []int{1}
}
func (m *MapEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapEntry.Unmarshal(m, b)
}
func (m *MapEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapEntry.Marshal(b, m, deterministic)
}
func (dst *MapEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapEntry.Merge(dst, src)
}
func (m *MapEntry) XXX_Size() int {
	return xxx_messageInfo_MapEntry.Size(m)
}
func (m *MapEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_MapEntry.DiscardUnknown(m)
}

var xxx_messageInfo_MapEntry proto.InternalMessageInfo

func (m *MapEntry) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *MapEntry) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type TokenMeta struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	Decimals             int32    `protobuf:"varint,3,opt,name=Decimals,proto3" json:"Decimals,omitempty"`
	InitialSupply        int64    `protobuf:"varint,4,opt,name=InitialSupply,proto3" json:"InitialSupply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenMeta) Reset()         { *m = TokenMeta{} }
func (m *TokenMeta) String() string { return proto.CompactTextString(m) }
func (*TokenMeta) ProtoMessage()    {}
func (*TokenMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_entities_8415b24e7cc06108, []int{2}
}
func (m *TokenMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenMeta.Unmarshal(m, b)
}
func (m *TokenMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenMeta.Marshal(b, m, deterministic)
}
func (dst *TokenMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenMeta.Merge(dst, src)
}
func (m *TokenMeta) XXX_Size() int {
	return xxx_messageInfo_TokenMeta.Size(m)
}
func (m *TokenMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenMeta.DiscardUnknown(m)
}

var xxx_messageInfo_TokenMeta proto.InternalMessageInfo

func (m *TokenMeta) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TokenMeta) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *TokenMeta) GetDecimals() int32 {
	if m != nil {
		return m.Decimals
	}
	return 0
}

func (m *TokenMeta) GetInitialSupply() int64 {
	if m != nil {
		return m.InitialSupply
	}
	return 0
}

type NewChannelPostTx struct {
	Version              int32    `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Cid                  string   `protobuf:"bytes,3,opt,name=cid,proto3" json:"cid,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewChannelPostTx) Reset()         { *m = NewChannelPostTx{} }
func (m *NewChannelPostTx) String() string { return proto.CompactTextString(m) }
func (*NewChannelPostTx) ProtoMessage()    {}
func (*NewChannelPostTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_entities_8415b24e7cc06108, []int{3}
}
func (m *NewChannelPostTx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewChannelPostTx.Unmarshal(m, b)
}
func (m *NewChannelPostTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewChannelPostTx.Marshal(b, m, deterministic)
}
func (dst *NewChannelPostTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewChannelPostTx.Merge(dst, src)
}
func (m *NewChannelPostTx) XXX_Size() int {
	return xxx_messageInfo_NewChannelPostTx.Size(m)
}
func (m *NewChannelPostTx) XXX_DiscardUnknown() {
	xxx_messageInfo_NewChannelPostTx.DiscardUnknown(m)
}

var xxx_messageInfo_NewChannelPostTx proto.InternalMessageInfo

func (m *NewChannelPostTx) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *NewChannelPostTx) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *NewChannelPostTx) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *NewChannelPostTx) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type SubscribeIdentittyTx struct {
	Statt                int32    `protobuf:"varint,1,opt,name=statt,proto3" json:"statt,omitempty"`
	ConversationPubKey   []byte   `protobuf:"bytes,2,opt,name=conversation_pub_key,json=conversationPubKey,proto3" json:"conversation_pub_key,omitempty"`
	EncryptedMessage     string   `protobuf:"bytes,3,opt,name=encrypted_message,json=encryptedMessage,proto3" json:"encrypted_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeIdentittyTx) Reset()         { *m = SubscribeIdentittyTx{} }
func (m *SubscribeIdentittyTx) String() string { return proto.CompactTextString(m) }
func (*SubscribeIdentittyTx) ProtoMessage()    {}
func (*SubscribeIdentittyTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_entities_8415b24e7cc06108, []int{4}
}
func (m *SubscribeIdentittyTx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeIdentittyTx.Unmarshal(m, b)
}
func (m *SubscribeIdentittyTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeIdentittyTx.Marshal(b, m, deterministic)
}
func (dst *SubscribeIdentittyTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeIdentittyTx.Merge(dst, src)
}
func (m *SubscribeIdentittyTx) XXX_Size() int {
	return xxx_messageInfo_SubscribeIdentittyTx.Size(m)
}
func (m *SubscribeIdentittyTx) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeIdentittyTx.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeIdentittyTx proto.InternalMessageInfo

func (m *SubscribeIdentittyTx) GetStatt() int32 {
	if m != nil {
		return m.Statt
	}
	return 0
}

func (m *SubscribeIdentittyTx) GetConversationPubKey() []byte {
	if m != nil {
		return m.ConversationPubKey
	}
	return nil
}

func (m *SubscribeIdentittyTx) GetEncryptedMessage() string {
	if m != nil {
		return m.EncryptedMessage
	}
	return ""
}

type SubscribeChannelTx struct {
	Deposit              int32    `protobuf:"varint,1,opt,name=deposit,proto3" json:"deposit,omitempty"`
	SubscriptionPubKey   []byte   `protobuf:"bytes,2,opt,name=subscription_pub_key,json=subscriptionPubKey,proto3" json:"subscription_pub_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubscribeChannelTx) Reset()         { *m = SubscribeChannelTx{} }
func (m *SubscribeChannelTx) String() string { return proto.CompactTextString(m) }
func (*SubscribeChannelTx) ProtoMessage()    {}
func (*SubscribeChannelTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_entities_8415b24e7cc06108, []int{5}
}
func (m *SubscribeChannelTx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeChannelTx.Unmarshal(m, b)
}
func (m *SubscribeChannelTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeChannelTx.Marshal(b, m, deterministic)
}
func (dst *SubscribeChannelTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeChannelTx.Merge(dst, src)
}
func (m *SubscribeChannelTx) XXX_Size() int {
	return xxx_messageInfo_SubscribeChannelTx.Size(m)
}
func (m *SubscribeChannelTx) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeChannelTx.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeChannelTx proto.InternalMessageInfo

func (m *SubscribeChannelTx) GetDeposit() int32 {
	if m != nil {
		return m.Deposit
	}
	return 0
}

func (m *SubscribeChannelTx) GetSubscriptionPubKey() []byte {
	if m != nil {
		return m.SubscriptionPubKey
	}
	return nil
}

func init() {
	proto.RegisterType((*Identity)(nil), "Identity")
	proto.RegisterType((*MapEntry)(nil), "MapEntry")
	proto.RegisterType((*TokenMeta)(nil), "TokenMeta")
	proto.RegisterType((*NewChannelPostTx)(nil), "NewChannelPostTx")
	proto.RegisterType((*SubscribeIdentittyTx)(nil), "SubscribeIdentittyTx")
	proto.RegisterType((*SubscribeChannelTx)(nil), "SubscribeChannelTx")
}

func init() { proto.RegisterFile("entities.proto", fileDescriptor_entities_8415b24e7cc06108) }

var fileDescriptor_entities_8415b24e7cc06108 = []byte{
	// 380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xdd, 0x8a, 0xdb, 0x30,
	0x10, 0x85, 0x71, 0xfe, 0x6a, 0x0f, 0x6d, 0x49, 0x45, 0x28, 0xa1, 0xa5, 0x10, 0x4c, 0x2f, 0x02,
	0x85, 0x52, 0xda, 0x47, 0x68, 0x7b, 0x11, 0x96, 0x84, 0xe0, 0xe4, 0xde, 0x2b, 0xdb, 0xb3, 0x1b,
	0x11, 0x5b, 0x12, 0x92, 0x9c, 0x44, 0xcf, 0xb0, 0x2f, 0xbd, 0x48, 0xb6, 0xb2, 0x59, 0xd8, 0xbb,
	0x39, 0xe7, 0xd8, 0x33, 0xdf, 0x48, 0x82, 0x8f, 0xc8, 0x0d, 0x33, 0x0c, 0xf5, 0x4f, 0xa9, 0x84,
	0x11, 0x69, 0x01, 0xf1, 0xaa, 0xf2, 0x9e, 0x25, 0xdf, 0x00, 0x1e, 0x98, 0xd2, 0x26, 0xe7, 0xb4,
	0xc1, 0x79, 0xb4, 0x88, 0x96, 0x49, 0x96, 0x78, 0x67, 0x43, 0x1b, 0x24, 0x5f, 0x21, 0xa9, 0x69,
	0x48, 0x07, 0x3e, 0x8d, 0x9d, 0xe1, 0xc3, 0x2f, 0x10, 0xb7, 0x1a, 0x95, 0xcf, 0x86, 0x5d, 0x16,
	0x74, 0xfa, 0x1b, 0xe2, 0x35, 0x95, 0xff, 0xb9, 0x51, 0x96, 0x4c, 0x61, 0x78, 0x44, 0xdb, 0x37,
	0x77, 0x25, 0x99, 0xc1, 0xf8, 0x44, 0xeb, 0x36, 0xb4, 0xec, 0x44, 0x6a, 0x21, 0xd9, 0x8b, 0x23,
	0xf2, 0x35, 0x1a, 0x4a, 0x08, 0x8c, 0x36, 0x2f, 0x48, 0xbe, 0x26, 0x9f, 0x61, 0xb2, 0xb3, 0x4d,
	0x21, 0xea, 0xfe, 0xbf, 0x5e, 0x39, 0x90, 0x7f, 0x58, 0xb2, 0x86, 0xd6, 0xda, 0x83, 0x8c, 0xb3,
	0xab, 0x26, 0xdf, 0xe1, 0xc3, 0x8a, 0x33, 0xc3, 0x68, 0xbd, 0x6b, 0xa5, 0xac, 0xed, 0x7c, 0xb4,
	0x88, 0x96, 0xc3, 0xec, 0xb5, 0x99, 0x1e, 0x60, 0xba, 0xc1, 0xf3, 0xdf, 0x03, 0xe5, 0x1c, 0xeb,
	0xad, 0xd0, 0x66, 0x7f, 0x21, 0x73, 0x78, 0x77, 0x42, 0xa5, 0x99, 0xe0, 0x1e, 0x62, 0x9c, 0x05,
	0xe9, 0xf0, 0xc5, 0x99, 0xa3, 0x0a, 0xf8, 0x5e, 0xb8, 0x35, 0x4b, 0x56, 0xf5, 0x27, 0xe1, 0x4a,
	0xb7, 0x43, 0x45, 0x0d, 0xf5, 0x23, 0xdf, 0x67, 0xbe, 0x4e, 0x9f, 0x22, 0x98, 0xed, 0xda, 0x42,
	0x97, 0x8a, 0x15, 0xd8, 0x5f, 0x83, 0xb1, 0xfb, 0x8b, 0x6b, 0xaa, 0x0d, 0x35, 0xa6, 0x1f, 0xd6,
	0x09, 0xf2, 0x0b, 0x66, 0xa5, 0xe0, 0x6e, 0x30, 0x35, 0x4c, 0xf0, 0x5c, 0xb6, 0x45, 0xee, 0x0e,
	0x73, 0xe0, 0x5b, 0x92, 0xdb, 0x6c, 0xdb, 0x16, 0x77, 0x68, 0xc9, 0x0f, 0xf8, 0x84, 0xbc, 0x54,
	0x56, 0x1a, 0xac, 0xf2, 0x06, 0xb5, 0xa6, 0x8f, 0xe1, 0x7a, 0xa6, 0xd7, 0x60, 0xdd, 0xf9, 0xe9,
	0x3d, 0x90, 0x2b, 0x4c, 0xbf, 0x7d, 0xb7, 0x79, 0x85, 0x52, 0x68, 0x16, 0x60, 0x82, 0x74, 0x38,
	0xba, 0xfb, 0x5e, 0xbe, 0x85, 0x73, 0x9b, 0x75, 0x38, 0xc5, 0xc4, 0xbf, 0xb9, 0x3f, 0xcf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xd1, 0x77, 0x1b, 0xfa, 0x85, 0x02, 0x00, 0x00,
}
